// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userIdentity: __t.identity().name("user_identity"),
  serverId: __t.u64().name("server_id"),
  feature: __t.string(),
  inputTokens: __t.u32().name("input_tokens"),
  outputTokens: __t.u32().name("output_tokens"),
  costMicros: __t.u64().name("cost_micros"),
  createdAt: __t.timestamp().name("created_at"),
});
