// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  serverId: __t.u64().primaryKey().name("server_id"),
  enabled: __t.bool(),
  askEnabled: __t.bool().name("ask_enabled"),
  summarizeEnabled: __t.bool().name("summarize_enabled"),
  monthlyTokenBudget: __t.u64().name("monthly_token_budget"),
  tokensUsedThisMonth: __t.u64().name("tokens_used_this_month"),
  sourceChannelIds: __t.string().name("source_channel_ids"),
  indexingEnabledByDefault: __t.bool().name("indexing_enabled_by_default"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
