// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  serverId: __t.u64().name("server_id"),
  channelId: __t.u64().name("channel_id"),
  threadId: __t.u64().name("thread_id"),
  userIdentity: __t.identity().name("user_identity"),
  question: __t.string(),
  status: __t.string(),
  answerMessageId: __t.u64().name("answer_message_id"),
  errorMessage: __t.string().name("error_message"),
  createdAt: __t.timestamp().name("created_at"),
  answeredAt: __t.timestamp().name("answered_at"),
});
