// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  channelId: __t.u64().primaryKey().name("channel_id"),
  indexingEnabled: __t.bool().name("indexing_enabled"),
  roleLabel: __t.string().name("role_label"),
  authorityWeight: __t.u32().name("authority_weight"),
  pinnedContext: __t.string().name("pinned_context"),
  updatedAt: __t.timestamp().name("updated_at"),
});
