// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  serverId: __t.u64().name("server_id"),
  name: __t.string(),
  topic: __t.string(),
  position: __t.i32(),
  categoryId: __t.u64().name("category_id"),
  slowmodeSeconds: __t.i32().name("slowmode_seconds"),
  lastMessageId: __t.u64().name("last_message_id"),
  createdAt: __t.timestamp().name("created_at"),
});
