// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AssignRoleReducer from "./assign_role_reducer";
import ClaimSuperAdminReducer from "./claim_super_admin_reducer";
import CreateAskRequestReducer from "./create_ask_request_reducer";
import CreateCategoryReducer from "./create_category_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateRoleReducer from "./create_role_reducer";
import CreateServerReducer from "./create_server_reducer";
import CreateThreadReducer from "./create_thread_reducer";
import DeleteCategoryReducer from "./delete_category_reducer";
import DeleteChannelReducer from "./delete_channel_reducer";
import DeleteChannelPermissionOverrideReducer from "./delete_channel_permission_override_reducer";
import DeleteInviteReducer from "./delete_invite_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteRoleReducer from "./delete_role_reducer";
import DeleteServerReducer from "./delete_server_reducer";
import DismissNotificationReducer from "./dismiss_notification_reducer";
import EditMessageReducer from "./edit_message_reducer";
import EnsureAiConfigReducer from "./ensure_ai_config_reducer";
import FailAskRequestReducer from "./fail_ask_request_reducer";
import GrantSpecialRoleReducer from "./grant_special_role_reducer";
import GrantSuperAdminReducer from "./grant_super_admin_reducer";
import JoinAsBotReducer from "./join_as_bot_reducer";
import JoinServerReducer from "./join_server_reducer";
import KickMemberReducer from "./kick_member_reducer";
import LeaveServerReducer from "./leave_server_reducer";
import MoveChannelReducer from "./move_channel_reducer";
import PinMessageReducer from "./pin_message_reducer";
import ReseedDefaultServerReducer from "./reseed_default_server_reducer";
import ResolveAskRequestReducer from "./resolve_ask_request_reducer";
import RevokeSpecialRoleReducer from "./revoke_special_role_reducer";
import RevokeSuperAdminReducer from "./revoke_super_admin_reducer";
import RevokeSuperAdminSelfReducer from "./revoke_super_admin_self_reducer";
import RotateDevAdminSecretReducer from "./rotate_dev_admin_secret_reducer";
import SeedDevAdminSecretReducer from "./seed_dev_admin_secret_reducer";
import SendMessageReducer from "./send_message_reducer";
import SendServerInviteReducer from "./send_server_invite_reducer";
import SetChannelAiConfigReducer from "./set_channel_ai_config_reducer";
import SetChannelPermissionOverrideReducer from "./set_channel_permission_override_reducer";
import SetMemberRoleReducer from "./set_member_role_reducer";
import SetNameReducer from "./set_name_reducer";
import SetNicknameReducer from "./set_nickname_reducer";
import SetProfileReducer from "./set_profile_reducer";
import SetSlowmodeReducer from "./set_slowmode_reducer";
import SetStatusReducer from "./set_status_reducer";
import SetTypingReducer from "./set_typing_reducer";
import ToggleReactionReducer from "./toggle_reaction_reducer";
import UnassignRoleReducer from "./unassign_role_reducer";
import UnpinMessageReducer from "./unpin_message_reducer";
import UpdateAiConfigReducer from "./update_ai_config_reducer";
import UpdateCategoryReducer from "./update_category_reducer";
import UpdateChannelReducer from "./update_channel_reducer";
import UpdateReadStateReducer from "./update_read_state_reducer";
import UpdateRoleReducer from "./update_role_reducer";
import UpdateServerReducer from "./update_server_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AiAuditRow from "./ai_audit_table";
import AiConfigRow from "./ai_config_table";
import AskRequestRow from "./ask_request_table";
import CategoryRow from "./category_table";
import ChannelRow from "./channel_table";
import ChannelAiConfigRow from "./channel_ai_config_table";
import ChannelPermissionOverrideRow from "./channel_permission_override_table";
import DevAdminAuditRow from "./dev_admin_audit_table";
import InviteRow from "./invite_table";
import MemberRoleRow from "./member_role_table";
import MessageRow from "./message_table";
import NotificationRow from "./notification_table";
import RateLimitRow from "./rate_limit_table";
import ReactionRow from "./reaction_table";
import ReadStateRow from "./read_state_table";
import ServerRow from "./server_table";
import ServerMemberRow from "./server_member_table";
import ServerRoleRow from "./server_role_table";
import SpecialChatRoleRow from "./special_chat_role_table";
import SuperAdminRow from "./super_admin_table";
import ThreadRow from "./thread_table";
import TypingRow from "./typing_table";
import UserRow from "./user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ai_audit: __table({
    name: 'ai_audit',
    indexes: [
      { accessor: 'id', name: 'ai_audit_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byUser', name: 'ai_audit_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'ai_audit_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiAuditRow),
  ai_config: __table({
    name: 'ai_config',
    indexes: [
      { accessor: 'serverId', name: 'ai_config_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'ai_config_server_id_key', constraint: 'unique', columns: ['serverId'] },
    ],
  }, AiConfigRow),
  ask_request: __table({
    name: 'ask_request',
    indexes: [
      { accessor: 'byChannel', name: 'ask_request_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'id', name: 'ask_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byStatus', name: 'ask_request_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'ask_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AskRequestRow),
  category: __table({
    name: 'category',
    indexes: [
      { accessor: 'id', name: 'category_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byServerId', name: 'category_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'category_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CategoryRow),
  channel: __table({
    name: 'channel',
    indexes: [
      { accessor: 'id', name: 'channel_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byServerId', name: 'channel_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'channel_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChannelRow),
  channel_ai_config: __table({
    name: 'channel_ai_config',
    indexes: [
      { accessor: 'channelId', name: 'channel_ai_config_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
    ],
    constraints: [
      { name: 'channel_ai_config_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, ChannelAiConfigRow),
  channel_permission_override: __table({
    name: 'channel_permission_override',
    indexes: [
      { accessor: 'byChannelId', name: 'channel_permission_override_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'id', name: 'channel_permission_override_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'channel_permission_override_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChannelPermissionOverrideRow),
  dev_admin_audit: __table({
    name: 'dev_admin_audit',
    indexes: [
      { accessor: 'id', name: 'dev_admin_audit_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byUser', name: 'dev_admin_audit_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'dev_admin_audit_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DevAdminAuditRow),
  invite: __table({
    name: 'invite',
    indexes: [
      { accessor: 'code', name: 'invite_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'id', name: 'invite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'invite_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'invite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InviteRow),
  member_role: __table({
    name: 'member_role',
    indexes: [
      { accessor: 'id', name: 'member_role_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byRoleId', name: 'member_role_role_id_idx_btree', algorithm: 'btree', columns: [
        'roleId',
      ] },
      { accessor: 'byServerId', name: 'member_role_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'member_role_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemberRoleRow),
  message: __table({
    name: 'message',
    indexes: [
      { accessor: 'byChannelId', name: 'message_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byThreadId', name: 'message_thread_id_idx_btree', algorithm: 'btree', columns: [
        'threadId',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  notification: __table({
    name: 'notification',
    indexes: [
      { accessor: 'id', name: 'notification_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byRecipient', name: 'notification_recipient_identity_idx_btree', algorithm: 'btree', columns: [
        'recipientIdentity',
      ] },
    ],
    constraints: [
      { name: 'notification_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NotificationRow),
  rate_limit: __table({
    name: 'rate_limit',
    indexes: [
      { accessor: 'id', name: 'rate_limit_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'rate_limit_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'rate_limit_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'rate_limit_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, RateLimitRow),
  reaction: __table({
    name: 'reaction',
    indexes: [
      { accessor: 'id', name: 'reaction_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byMessageId', name: 'reaction_message_id_idx_btree', algorithm: 'btree', columns: [
        'messageId',
      ] },
    ],
    constraints: [
      { name: 'reaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReactionRow),
  read_state: __table({
    name: 'read_state',
    indexes: [
      { accessor: 'id', name: 'read_state_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byUserIdentity', name: 'read_state_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'read_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReadStateRow),
  server: __table({
    name: 'server',
    indexes: [
      { accessor: 'id', name: 'server_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'server_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerRow),
  server_member: __table({
    name: 'server_member',
    indexes: [
      { accessor: 'id', name: 'server_member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byServerId', name: 'server_member_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
      { accessor: 'byUserIdentity', name: 'server_member_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'server_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerMemberRow),
  server_role: __table({
    name: 'server_role',
    indexes: [
      { accessor: 'id', name: 'server_role_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byServerId', name: 'server_role_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'server_role_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerRoleRow),
  special_chat_role: __table({
    name: 'special_chat_role',
    indexes: [
      { accessor: 'id', name: 'special_chat_role_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byServerId', name: 'special_chat_role_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'special_chat_role_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpecialChatRoleRow),
  super_admin: __table({
    name: 'super_admin',
    indexes: [
      { accessor: 'userIdentity', name: 'super_admin_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'super_admin_user_identity_key', constraint: 'unique', columns: ['userIdentity'] },
    ],
  }, SuperAdminRow),
  thread: __table({
    name: 'thread',
    indexes: [
      { accessor: 'byChannelId', name: 'thread_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'id', name: 'thread_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byParentId', name: 'thread_parent_message_id_idx_btree', algorithm: 'btree', columns: [
        'parentMessageId',
      ] },
    ],
    constraints: [
      { name: 'thread_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ThreadRow),
  typing: __table({
    name: 'typing',
    indexes: [
      { accessor: 'userIdentity', name: 'typing_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'typing_user_identity_key', constraint: 'unique', columns: ['userIdentity'] },
    ],
  }, TypingRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("assign_role", AssignRoleReducer),
  __reducerSchema("claim_super_admin", ClaimSuperAdminReducer),
  __reducerSchema("create_ask_request", CreateAskRequestReducer),
  __reducerSchema("create_category", CreateCategoryReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_role", CreateRoleReducer),
  __reducerSchema("create_server", CreateServerReducer),
  __reducerSchema("create_thread", CreateThreadReducer),
  __reducerSchema("delete_category", DeleteCategoryReducer),
  __reducerSchema("delete_channel", DeleteChannelReducer),
  __reducerSchema("delete_channel_permission_override", DeleteChannelPermissionOverrideReducer),
  __reducerSchema("delete_invite", DeleteInviteReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_role", DeleteRoleReducer),
  __reducerSchema("delete_server", DeleteServerReducer),
  __reducerSchema("dismiss_notification", DismissNotificationReducer),
  __reducerSchema("edit_message", EditMessageReducer),
  __reducerSchema("ensure_ai_config", EnsureAiConfigReducer),
  __reducerSchema("fail_ask_request", FailAskRequestReducer),
  __reducerSchema("grant_special_role", GrantSpecialRoleReducer),
  __reducerSchema("grant_super_admin", GrantSuperAdminReducer),
  __reducerSchema("join_as_bot", JoinAsBotReducer),
  __reducerSchema("join_server", JoinServerReducer),
  __reducerSchema("kick_member", KickMemberReducer),
  __reducerSchema("leave_server", LeaveServerReducer),
  __reducerSchema("move_channel", MoveChannelReducer),
  __reducerSchema("pin_message", PinMessageReducer),
  __reducerSchema("reseed_default_server", ReseedDefaultServerReducer),
  __reducerSchema("resolve_ask_request", ResolveAskRequestReducer),
  __reducerSchema("revoke_special_role", RevokeSpecialRoleReducer),
  __reducerSchema("revoke_super_admin", RevokeSuperAdminReducer),
  __reducerSchema("revoke_super_admin_self", RevokeSuperAdminSelfReducer),
  __reducerSchema("rotate_dev_admin_secret", RotateDevAdminSecretReducer),
  __reducerSchema("seed_dev_admin_secret", SeedDevAdminSecretReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("send_server_invite", SendServerInviteReducer),
  __reducerSchema("set_channel_ai_config", SetChannelAiConfigReducer),
  __reducerSchema("set_channel_permission_override", SetChannelPermissionOverrideReducer),
  __reducerSchema("set_member_role", SetMemberRoleReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_nickname", SetNicknameReducer),
  __reducerSchema("set_profile", SetProfileReducer),
  __reducerSchema("set_slowmode", SetSlowmodeReducer),
  __reducerSchema("set_status", SetStatusReducer),
  __reducerSchema("set_typing", SetTypingReducer),
  __reducerSchema("toggle_reaction", ToggleReactionReducer),
  __reducerSchema("unassign_role", UnassignRoleReducer),
  __reducerSchema("unpin_message", UnpinMessageReducer),
  __reducerSchema("update_ai_config", UpdateAiConfigReducer),
  __reducerSchema("update_category", UpdateCategoryReducer),
  __reducerSchema("update_channel", UpdateChannelReducer),
  __reducerSchema("update_read_state", UpdateReadStateReducer),
  __reducerSchema("update_role", UpdateRoleReducer),
  __reducerSchema("update_server", UpdateServerReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

