// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  recipientIdentity: __t.identity().name("recipient_identity"),
  type: __t.string(),
  inviteCode: __t.string().name("invite_code"),
  serverId: __t.u64().name("server_id"),
  serverName: __t.string().name("server_name"),
  senderName: __t.string().name("sender_name"),
  createdAt: __t.timestamp().name("created_at"),
});
