// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  ownerId: __t.identity().name("owner_id"),
  isPublic: __t.bool().name("is_public"),
  createdAt: __t.timestamp().name("created_at"),
  iconUrl: __t.string().name("icon_url"),
  bannerColor: __t.string().name("banner_color"),
  traits: __t.string(),
});
