// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiAudit = __t.object("AiAudit", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  serverId: __t.u64(),
  feature: __t.string(),
  inputTokens: __t.u32(),
  outputTokens: __t.u32(),
  costMicros: __t.u64(),
  createdAt: __t.timestamp(),
});
export type AiAudit = __Infer<typeof AiAudit>;

export const AiConfig = __t.object("AiConfig", {
  serverId: __t.u64(),
  enabled: __t.bool(),
  askEnabled: __t.bool(),
  summarizeEnabled: __t.bool(),
  monthlyTokenBudget: __t.u64(),
  tokensUsedThisMonth: __t.u64(),
  sourceChannelIds: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AiConfig = __Infer<typeof AiConfig>;

export const AskRequest = __t.object("AskRequest", {
  id: __t.u64(),
  serverId: __t.u64(),
  channelId: __t.u64(),
  threadId: __t.u64(),
  userIdentity: __t.identity(),
  question: __t.string(),
  status: __t.string(),
  answerMessageId: __t.u64(),
  errorMessage: __t.string(),
  createdAt: __t.timestamp(),
  answeredAt: __t.timestamp(),
});
export type AskRequest = __Infer<typeof AskRequest>;

export const Category = __t.object("Category", {
  id: __t.u64(),
  serverId: __t.u64(),
  name: __t.string(),
  position: __t.i32(),
});
export type Category = __Infer<typeof Category>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  serverId: __t.u64(),
  name: __t.string(),
  topic: __t.string(),
  position: __t.i32(),
  categoryId: __t.u64(),
  slowmodeSeconds: __t.i32(),
  lastMessageId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const Invite = __t.object("Invite", {
  id: __t.u64(),
  code: __t.string(),
  serverId: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAt: __t.u64(),
  maxUses: __t.i32(),
  usesCount: __t.i32(),
});
export type Invite = __Infer<typeof Invite>;

export const MemberRole = __t.object("MemberRole", {
  id: __t.u64(),
  serverId: __t.u64(),
  userIdentity: __t.identity(),
  roleId: __t.u64(),
  assignedAt: __t.timestamp(),
});
export type MemberRole = __Infer<typeof MemberRole>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  channelId: __t.u64(),
  threadId: __t.u64(),
  replyToId: __t.u64(),
  authorId: __t.identity(),
  text: __t.string(),
  attachmentUrl: __t.string(),
  pinned: __t.bool(),
  sent: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
});
export type Message = __Infer<typeof Message>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipientIdentity: __t.identity(),
  type: __t.string(),
  inviteCode: __t.string(),
  serverId: __t.u64(),
  serverName: __t.string(),
  senderName: __t.string(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const RateLimit = __t.object("RateLimit", {
  id: __t.u64(),
  key: __t.string(),
  userIdentity: __t.identity(),
  channelId: __t.u64(),
  lastMessageAt: __t.timestamp(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const Reaction = __t.object("Reaction", {
  id: __t.u64(),
  messageId: __t.u64(),
  emoji: __t.string(),
  userIdentity: __t.identity(),
  reactedAt: __t.timestamp(),
});
export type Reaction = __Infer<typeof Reaction>;

export const ReadState = __t.object("ReadState", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  channelId: __t.u64(),
  lastReadMessageId: __t.u64(),
});
export type ReadState = __Infer<typeof ReadState>;

export const Server = __t.object("Server", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  ownerId: __t.identity(),
  isPublic: __t.bool(),
  createdAt: __t.timestamp(),
  iconUrl: __t.string(),
  bannerColor: __t.string(),
  traits: __t.string(),
});
export type Server = __Infer<typeof Server>;

export const ServerMember = __t.object("ServerMember", {
  id: __t.u64(),
  serverId: __t.u64(),
  userIdentity: __t.identity(),
  nickname: __t.option(__t.string()),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ServerMember = __Infer<typeof ServerMember>;

export const ServerRole = __t.object("ServerRole", {
  id: __t.u64(),
  serverId: __t.u64(),
  name: __t.string(),
  color: __t.string(),
  position: __t.i32(),
  permissions: __t.u64(),
  isDefault: __t.bool(),
});
export type ServerRole = __Infer<typeof ServerRole>;

export const SpecialChatRole = __t.object("SpecialChatRole", {
  id: __t.u64(),
  serverId: __t.u64(),
  userIdentity: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type SpecialChatRole = __Infer<typeof SpecialChatRole>;

export const SuperAdmin = __t.object("SuperAdmin", {
  userIdentity: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type SuperAdmin = __Infer<typeof SuperAdmin>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  channelId: __t.u64(),
  parentMessageId: __t.u64(),
  name: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const Typing = __t.object("Typing", {
  userIdentity: __t.identity(),
  channelId: __t.u64(),
  startedAt: __t.timestamp(),
});
export type Typing = __Infer<typeof Typing>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  avatarColor: __t.string(),
  bio: __t.string(),
  pronouns: __t.string(),
  status: __t.string(),
  online: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type User = __Infer<typeof User>;

